services:
  - type: web
    name: PTz-appointment-booking
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn Appointment_Booking.wsgi:application"
    staticPublishPath: staticfiles
    healthCheckPath: /
    autoDeploy: true
