# Generated by Django 5.1.1 on 2024-11-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_customuser_is_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ticket_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
