# Generated by Django 5.1.1 on 2024-11-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_appointment_patient_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_contact',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
