# Generated by Django 5.1.1 on 2024-11-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_appointment_patient_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ticket_id',
            field=models.CharField(default=None, editable=False, max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
