# Generated by Django 5.1.1 on 2024-11-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_appointment_issued_at_appointment_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
