# Generated by Django 5.1.1 on 2024-11-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
