# Generated by Django 5.1.1 on 2024-11-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_contact_is_replied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile',
        ),
    ]
